@startuml
skinparam classAttributeIconSize 0
class com.javeriana.model.Artist {
    - id: UUID
    - name: String

    + Artist(id: UUID, name: String)
    + Artist(name: String)
}

class com.javeriana.model.Customer {
    - id: UUID
    - username: String
    - password: String
    - name: String
    - lastName: String
    - age: int

    + Customer(username: String, password: String, name: String, lastName: String, age: int)
}

class com.javeriana.model.Playlist {
    - id: UUID
    - name: String

    + playList(name: String)

}

class com.javeriana.model.Song {
    - id: UUID
    - name: String
    - genre: String
    - durationInSeconds: int
    - album: String

    + Song(name: String, genre: String, durationInSeconds: int, album: String)
}

class Main {


}

@enduml