@startuml
skinparam classAttributeIconSize 0
class com.javeriana.model.Artist $Artist {
    - id: UUID
    - name: String

    + Artist(id: UUID, name: String)
    + Artist(name: String)
}

class com.javeriana.model.Customer $Customer {
    - id: UUID
    - username: String
    - password: String
    - name: String
    - lastName: String
    - age: int

    + Customer(username: String, password: String, name: String, lastName: String, age: int)
    + Customer(UUID: id, username: String, password: String, name: String, lastName: String, age: int, List<Artist> followedArtists, List<playList> playLists)


    + getId() : UUID
    + getUsername() : String
    + setUsername(String username)
    + getPassword() : String
    + setPassword(String password)
    + getName() : String
    + setName(String name)
    + getLastName() : String
    + setLastName(String lastName)
    + getAge() : int
    + setAge(int age)
    + removePlaylist(UUID id) : boolean
    + removeArtist(UUID artistId)
    + removeSongFromPlayLists(UUID songId)
    + toString() : String
    - getPlaylistById(UUID id) : Playlist
    - getArtistById(UUID id) : Artist
}

class com.javeriana.model.Playlist $Playlist {
    - id: UUID
    - name: String

    + playList(name: String)
    + playList(UUID: id, name: String, List<Song> songs)


    + getId() : UUID
    + getName() : String
    + setName(String name)
    + getSongs() : List<Song>
    + removeSong(UUID songId)
    + removeSongsOfArtist(UUID artistId)
    + toString() : String
    - getSongById(UUID songId) : Song
}

class com.javeriana.model.Song $Song {
    - id: UUID
    - name: String
    - genre: String
    - durationInSeconds: int
    - album: String

    + Song(String name, String genre, int durationInSeconds, String album, List<Artist> artists)
    + Song(UUID id, String name, String genre, int durationInSeconds, String album, List<Artist> artists)
    + getId() : UUID
    + getName() : String
    + setName(String name)
    + getGenre() : String
    + setGenre(String genre)
    + getDurationInSeconds() : int
    + setDurationInSeconds(int durationInSeconds)
    + getAlbum() : String
    + setAlbum(String album)
    + getArtists() : List<Artist>
    + hasArtist(UUID artistId) : boolean
    + toString() : String
}

class com.javeriana.service.ArtistService $ArtistService {

    + ArtistService()


    + getArtists() : List<Artist>
    + addArtist(String name) : Artist
    + getArtistById(UUID id) : Artist
    + removeArtist(UUID id) : boolean
    + getArtistsToString() : List<String>
    + getArtistsByIds(List<UUID> artists) : List<Artist>
}

class com.javeriana.service.CustomerAdminService $CustomerAdminService {

    + CustomerAdminService()


    + getCustomers() : List<Customer>
    + addCustomer(String username, String password, String name, String lastName, int age)
    + removeCustomer(UUID id) : boolean
    + getCustomerById(UUID id) : Customer
    + getCustomersToString() : List<String>
    + removePlaylistFromCustomers(UUID playlistId)
    + removeArtistFromCustomers(UUID artistId)
}

class com.javeriana.service.SongService $SongService {

    + SongService()


    + getSongs() : List<Song>
    + addSong(String name, String genre, int durationInSeconds, String album, List<Artist> artists)
    + removeSong(UUID songId) : boolean
    + getSongById(UUID songId) : Song
    + removeSongsOfArtist(UUID artistId)
    + getSongsToString() : List<String>
}

class com.javeriana.service.PlaylistService $PlaylistService {

    + PlaylistService()
    + getPlaylists() : List<Playlist>
    + addPlaylist(String name)
    + removePlaylist(UUID id) : boolean
    + getPlaylistById(UUID id) : Playlist
    + removeSongsOfArtist(UUID artistId)
    + getPlaylistsToString() : List<String>
    + removeSongFromPlaylists(UUID uuid)
}

class com.javeriana.controller.AdminController $AdminController {

     + AdminController(ArtistService artistService, CustomerAdminService customerAdminService, SongService songService, PlaylistService playlistService)
     + addArtist(String name)
     + removeArtist(String id)
     + addCustomer(String username, String password, String name, String lastName, int age)
     + removeCustomer(String id)
     + addSong(String name, String genre, int durationInSeconds, String album, List<String> artistIds)
     + removeSong(String id)
     + addPlaylist(String name)
     + removePlaylist(String id)
     + getArtistsToString() : List<String>
     + getCustomersToString() : List<String>
     + getSongsToString() : List<String>
     + getPlaylistsToString() : List<String>

}

class com.javeriana.views.AdminView $AdminView {

    - scanner : Scanner

    + AdminView(AdminController adminController, Scanner scanner)
    + showMenu()
    - showPlaylists()
    - showArtists()
    - showCustomers()
    - showSongs()
    - removePlaylist()
    - addPlaylist()
    - addCustomer()
    - removeCustomer()
    - removeSong()
    - addSong()
    - removeArtist()
    - addArtist()
}

class Main $Main {

    + Main()
    + main(args: String[]): void


}

' Relaciones
com.javeriana.model.Customer "1" o-> "0..*" com.javeriana.model.Playlist : Has a list (playlists) >
com.javeriana.model.Customer "1" o--> "0..*" com.javeriana.model.Artist : Has a list (followedArtists) >
com.javeriana.model.Playlist "1" o--> "0..*" com.javeriana.model.Song : Has a list (songs) >
com.javeriana.model.Song "1" *-> "1..*" com.javeriana.model.Artist : Has a list (artists) >

com.javeriana.service.ArtistService "1" o--> "*" com.javeriana.model.Artist : Has a list (artists) >
com.javeriana.service.CustomerAdminService "1" o--> "*" com.javeriana.model.Customer : Has a list (customers) >
com.javeriana.service.SongService "1" o-> "*" com.javeriana.model.Song : Has a list (songs) >
com.javeriana.service.PlaylistService "1" o-> "*" com.javeriana.model.Playlist : Has a list (playLists) >

com.javeriana.controller.AdminController "1" *--> "1" com.javeriana.service.ArtistService : Uses >
com.javeriana.controller.AdminController "1" *--> "1" com.javeriana.service.CustomerAdminService : Uses >
com.javeriana.controller.AdminController "1" *--> "1" com.javeriana.service.SongService : Uses >
com.javeriana.controller.AdminController "1" *--> "1" com.javeriana.service.PlaylistService : Uses >

com.javeriana.views.AdminView "1" *--> "1" com.javeriana.controller.AdminController : Uses >

Main -down-> AdminView : Creates >

' Remover todo menos las clases dentro de models

' Remover Main
remove $Main

' Remover Vistas
remove $AdminView

' Remover Controladores
remove $AdminController

' Remover Servicios
remove $CustomerAdminService
remove $SongService
remove $PlaylistService
remove $ArtistService

/'
' Remover todo menos ArtistService y Artist

' Remover Main
remove $Main

' Remover Vistas
remove $AdminView

' Remover Controladores
remove $AdminController

' Remover Servicios
remove $CustomerAdminService
remove $SongService
remove $PlaylistService

' Remover Modelos
remove $Customer
remove $Song
remove $Playlist
'/

/'
' Remover todo menos CustomerAdminService y Customer

' Remover Main
remove $Main

' Remover Vistas
remove $AdminView

' Remover Controladores
remove $AdminController

' Remover Servicios
remove $SongService
remove $PlaylistService
remove $ArtistService

' Remover Modelos
remove $Artist
remove $Song
remove $Playlist
'/

/'
' Remover todo menos SongService y Song

' Remover Main
remove $Main

' Remover Vistas
remove $AdminView

' Remover Controladores
remove $AdminController

' Remover Servicios
remove $CustomerAdminService
remove $PlaylistService
remove $ArtistService

' Remover Modelos
remove $Artist
remove $Customer
remove $Playlist
'/

/'
' Remover todo menos PlaylistService y Playlist

' Remover Main
remove $Main

' Remover Vistas
remove $AdminView

' Remover Controladores
remove $AdminController

' Remover Servicios
remove $CustomerAdminService
remove $SongService
remove $ArtistService

' Remover Modelos
remove $Artist
remove $Customer
remove $Song
'/

/'
' Remover todo menos AdminController y los servicios

' Remover Main
remove $Main

' Remover Vistas
remove $AdminView

' Remover Modelos
remove $Artist
remove $Customer
remove $Song
remove $Playlist
'/

/'
' Remover todo menos AdminView y AdminController

' Remover Main
remove $Main

' Remover Modelos
remove $Artist
remove $Customer
remove $Song
remove $Playlist

' Remover Servicios
remove $CustomerAdminService
remove $SongService
remove $PlaylistService
remove $ArtistService
'/
/'
' Remover todo menos Main y AdminView

' Remover Controladores
remove $AdminController

' Remover Servicios
remove $CustomerAdminService
remove $SongService
remove $PlaylistService
remove $ArtistService

' Remover Modelos
remove $Artist
remove $Customer
remove $Song
remove $Playlist
'/

@enduml
